spring:
    datasource:
        password: ${db.password}
        url: ${db.url}
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${db.username}
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update